
{
    # JSON っぽい書き方をした YAML
    # 全般の設定
    'general': {

        # デバッグモードを有効にするか
        # 有効にした場合、表示されるログが増える
        'debug': True,

        # 利用するバックエンド
        # Mirakurun・EDCB から選択
        'backend': 'Mirakurun',

        # Mirakurun の HTTP URL
        # バックエンドに Mirakurun を選択した場合に利用される
        'mirakurun_url': 'http://192.168.1.11:40772',

        # EDCB (EpgTimerNW) の TCP URL
        # バックエンドに EDCB を選択した場合に利用される
        'edcb_url': 'tcp://0.0.0.1:4510',
    },

    # ライブストリームの設定
    'livestream': {

        # 利用するエンコーダー
        # FFmpeg・QSVEncC・NVEncC・VCEEncC から選択
        'encoder': 'QSVEncC',

        # 誰も見ていないライブストリームを何秒まで維持するか
        # 10 秒に設定したなら、10 秒間誰も見ていない状態が継続したらライブストリーム（エンコーダー）を終了する
        # 0 秒に設定するとリロードしただけでチューナーオープンとエンコードがやり直しになってしまうため、余裕をもたせておく事を推奨
        'max_alive_time': 10,
    }
}
